# Generated by Django 4.0.5 on 2022-07-04 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_pellido', models.CharField(max_length=50)),
                ('dni', models.IntegerField()),
                ('fecha_nacimiento', models.DateField()),
                ('ocupacion', models.CharField(max_length=50)),
            ],
        ),
    ]
