# Generated by Django 4.0.5 on 2022-07-05 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_familia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='familia',
            old_name='nombre_pellido',
            new_name='nombre_apellido',
        ),
    ]
