# Generated by Django 4.0.5 on 2022-07-05 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0003_rename_nombre_pellido_familia_nombre_apellido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='familia',
            old_name='fecha_nacimiento',
            new_name='fecha_actualizacion',
        ),
    ]
