# Generated by Django 4.0.5 on 2022-07-05 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0004_rename_fecha_nacimiento_familia_fecha_actualizacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familia',
            name='fecha_actualizacion',
            field=models.DateField(auto_now_add=True),
        ),
    ]
